/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-1',
  aws_cognito_identity_pool_id:
    'ap-southeast-1:23cce3c3-36f2-4b48-b69d-9248e536636a',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: 'ap-southeast-1_W1mhfjMVW',
  aws_user_pools_web_client_id: '4c3r4mg3qt4ci9659qrlcatdnk',
  oauth: {},
};

export default awsmobile;
